version: '3'
services:
  web:
    build:
      context: tasks/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    user: "5678"
    volumes:
      - .:/app