version: '3'
services:
  web:
    build: ./app
    image: 687648284088.dkr.ecr.us-east-1.amazonaws.com/todo:todo_web
      context: tasks/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    user: "5678"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DB_NAME=nc_tasks_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg
  
   nginx:
    build: ./nginx
    image: 687648284088.dkr.ecr.us-east-1.amazonaws.com/todo:todo_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web

  pg:
    container_name: pg_container
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: nc_tasks_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/final_project.sql:/docker-entrypoint-initdb.d/1-django-init.sql

# pgAdmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - pg  # Ensure pgAdmin starts after PostgreSQL
