version: "3.8"
services:
  web:
    build: ./tasks
    image: 687648284088.dkr.ecr.us-east-1.amazonaws.com/django_docker_aws:django_docker_aws_web
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./tasks/:/usr/src/tasks/
      #- static_volume:/usr/src/tasks/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tasks_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg

  pg:
    container_name: pg_container
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: nc_tasks_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/final_project.sql:/docker-entrypoint-initdb.d/1-django-init.sql